# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Fostering Greatness
# Description of the Site
description: A blog site that covers how-to articles, tech, the foster care system, and personal blogs from my experience in life.
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: gitfitdev@gmail.com
facebook_username: gitfitdev
twitter_username: gitfitdev
instagram_username: gitfitdev
linkedin_username: /
github_username:  gitfitdev
youtube_channel_id: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: gitfitdev

# Name of the Author
author-name:  Courtney Revada
# URL for the Image of the Author
author-image: ./assets/images/me.jpg
# 60 Words About the Author
author-about: My name is Courtney Revada, and I am a self taught web developer. Outside of my career I am a foster youth advocate who wishes to inspire those with care experience and help change the foster care system. I believe anyone can become successful in life regardless of your background. Let's join together in fostering greatness in us all!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/gitfitdev

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
